<?php

/* Author: Stephan Blanke */

$labels = array();
$labels['aliases'] = 'Aliase';
$labels['aliasesmanagealiases'] = 'Verwalte Aliase';
$labels['aliasesnewalias'] = 'Neuer Alias';
$labels['aliaseseditalias'] = 'Bearbeite Alias';
$labels['aliasesaliasname'] = 'Alias';
$labels['aliasesenable'] = 'Aktivieren/Deaktivieren';
$labels['aliasesstatustoggled'] = 'Status geändert';


$messages = array();
$messages['aliasesnoaliasname'] = 'Kein Alias-Name angegeben';
$messages['aliasesaliasexists'] = 'Alias existiert bereits';
$messages['aliasesaliasexistsindomain'] = 'Alias existiert bereits in Domäne';
$messages['aliasesaliasdeleteconfirm'] = 'Sind Sie sicher, dass Sie diesen Alias löschen wollen?';
$messages['aliasesaliasdeleted'] = 'Alias erfolgreich gelöscht';
$messages['aliasesaliasdeletederror'] = 'Alias konnte nicht gelöscht werden';
$messages['aliasesaliascreated'] = 'Alias erfolgreich angelegt';
$messages['aliasesaliascreatederror'] = 'Alias konnte nicht angelegt werden';
$messages['aliasesaliasupdated'] = 'Alias erfolgreich aktualisiert';
$messages['aliasesaliasupdatederror'] = 'Alias konnte nicht aktualisiert werden';
$messages['aliasesaliasnameerror'] = 'Alias-Name enthält ungültige Zeichen, erlaubt sind: a-z, A-Z, 0-9, _ und .';
$messages['aliasesnoalias'] = 'Keine Aliase gefunden';
$messages['aliasesinvalidalias'] = 'Alias-Name ungültig';
$messages['aliasesnovalidalias'] = 'Alias-Name leer';
$messages['aliasessuccessfullysaved'] = 'Alias erfolgreich gespeichert';
$messages['aliasesdriverconnecterror'] = 'Treiber-Verbindungsfehler';
$messages['aliasesdriverprocesserror'] = 'Treiber-Ausführungsfehler';
$messages['aliasesinternalerror'] = 'Treiber nicht gefunden';

?>
