<?php

/* Author: Gianluca Giacometti */

$labels = array();
$labels['aliases'] = 'Aliases';
$labels['aliasesmanagealiases'] = 'Manage aliases';
$labels['aliasesnewalias'] = 'New alias';
$labels['aliaseseditalias'] = 'Edit alias';
$labels['aliasesaliasname'] = 'Alias';
$labels['aliasesenablealias'] = 'Enable alias';
$labels['aliasesaliasenabled'] = 'Enabled';


$messages = array();
$messages['aliasesnoaliasname'] = 'No alias name specified';
$messages['aliasesaliasexists'] = 'Alias already exists';
$messages['aliasesaliasexistsindomain'] = 'Alias already exists in domain';
$messages['aliasesaliasdeleteconfirm'] = 'Are you sure you want to delete this alias?';
$messages['aliasesaliasdeleted'] = 'Alias deleted successfully';
$messages['aliasesaliasdeletederror'] = 'Error while deleting alias';
$messages['aliasesaliascreated'] = 'Alias created successfully';
$messages['aliasesaliascreatederror'] = 'Error while creating alias';
$messages['aliasesaliasupdated'] = 'Alias updated successfully';
$messages['aliasesaliasupdatederror'] = 'Error while updating alias';
$messages['aliasesaliasnameerror'] = 'Error in name format, allowed characters: a-z, A-Z, 0-9, _ and .';
$messages['aliasesnoalias'] = 'No aliases found';
$messages['aliasesinvalidalias'] = 'Alias name not valid';
$messages['aliasesnovalidalias'] = 'Alias name empty';
$messages['aliasessuccessfullysaved'] = 'Alias saved successfully';
$messages['aliasesdriverconnecterror'] = 'Driver connection error';
$messages['aliasesdriverprocesserror'] = 'Driver execution error';
$messages['aliasesinternalerror'] = 'Driver not found';

?>
