<?php

/* Author: Gianluca Giacometti */

$labels = array();
$labels['aliases'] = 'Nomi alternativi';
$labels['aliasesmanagealiases'] = 'Gestisci nomi alternativi';
$labels['aliasesnewalias'] = 'Nuovo nome alternativo';
$labels['aliaseseditalias'] = 'Modifica nome alternativo';
$labels['aliasesaliasname'] = 'Nome alternativo';
$labels['aliasesenablealias'] = 'Abilita nome alternativo';
$labels['aliasesaliasenabled'] = 'Abilitato';


$messages = array();
$messages['aliasesnoaliasname'] = 'Nessun nome specificato';
$messages['aliasesaliasexists'] = 'Nome alternativo già esistente';
$messages['aliasesaliasexistsindomain'] = 'Nome alternativo già esistente nel dominio';
$messages['aliasesaliasdeleteconfirm'] = 'Sei sicuro/a di di voler cancellare questo nome alternativo?';
$messages['aliasesaliasdeleted'] = 'Nome alternativo cancellato con successo';
$messages['aliasesaliasdeletederror'] = 'Impossibile cancellare il nome alternativo';
$messages['aliasesaliascreated'] = 'Nome alternativo creato con successo';
$messages['aliasesaliascreatederror'] = 'Impossibile creare il nome alternativo';
$messages['aliasesaliasupdated'] = 'Nome alternativo aggiornato con successo';
$messages['aliasesaliasupdatederror'] = 'Impossibile aggiornare il nome alternativo';
$messages['aliasesnoalias'] = 'Nessun nome alternativo trovato';
$messages['aliasesinvalidalias'] = 'Nome alternativo non valido';
$messages['aliasesnovalidalias'] = 'Nome alternativo vuoto';
$messages['aliasessuccessfullysaved'] = 'Nome alternativo salvato con successo';
$messages['aliasesdriverconnecterror'] = 'Errore di connessione del driver';
$messages['aliasesdriverprocesserror'] = 'Errore di esecuzione del driver';
$messages['aliasesinternalerror'] = 'Errore di lettura del driver';

?>
